"""main.py — shared orchestration for the mwp_contribution module.

Library file: no print() statements; all output goes to files.
Run the pipeline through run_classify.py — do not edit this file to change
classification behaviour; correct the AI_tables/*.csv instead.
"""
import os
from openpyxl.utils import column_index_from_string as ci

import mwp_data
import mwp_viz
import write_xlsx


def run_pipeline(cfg):
    """Full run: load -> classify -> tests -> workbook -> figures -> log.

    Returns (results_dataframe, tests, log_lines).
    """
    log = []
    tables = mwp_data.Tables(cfg['tables_dir'])
    df = mwp_data.load_form(cfg['input_xlsx'])
    log.append(f"Loaded '{mwp_data.SHEET}': {len(df)} rows x {df.shape[1]} columns")

    res = mwp_data.classify(df, tables, cfg['scoring'])
    log.append(f'Classified {len(res)} papers')

    tests = mwp_data.check_invariants(res, df)
    for name, ok, detail in tests:
        log.append(f"TEST {'PASS' if ok else 'FAIL'} — {name} {detail}")

    os.makedirs(cfg['output_dir'], exist_ok=True)

    # results as CSV for diff-friendly versioning
    csv_path = os.path.join(cfg['output_dir'], cfg['results_csv'])
    flat = res.copy()
    for c in ('Materials', 'Geometries'):
        flat[c] = flat[c].apply('; '.join)
    flat.drop(columns=['idx']).to_csv(csv_path, index=False)
    log.append(f'Results CSV: {csv_path}')

    # workbook
    empty_cols = mwp_data.find_empty_columns(df)
    au_lookup = {res.loc[k, 'Paper ID']:
                 ('' if df.iloc[res.loc[k, 'idx'], ci('AU') - 1] != df.iloc[
                     res.loc[k, 'idx'], ci('AU') - 1]  # NaN check
                  else str(df.iloc[res.loc[k, 'idx'], ci('AU') - 1]))
                 for k in res.index}
    xlsx_path = os.path.join(cfg['output_dir'], cfg['workbook_name'])
    write_xlsx.write_workbook(res, empty_cols, au_lookup, xlsx_path, cfg['xlsx'])
    log.append(f'Workbook: {xlsx_path} ({len(empty_cols)} empty form columns)')

    # figures
    fig_dir = os.path.join(cfg['output_dir'], cfg['figures_dirname'])
    paths = mwp_viz.make_all_figures(res, fig_dir, cfg['viz'])
    log.append(f'Figures: {len(paths)} files in {fig_dir}')

    # headline summary into the log
    for col in ('MWP Technique', 'TC MWP Relevance', 'Primary', 'Confidence'):
        log.append(f'{col}: {res[col].value_counts().to_dict()}')

    log_path = os.path.join(cfg['output_dir'], cfg['log_name'])
    with open(log_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(log) + '\n')
    return res, tests, log
